// Generated by Xata Codegen 0.23.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "dogs",
    columns: [
      { name: "name", type: "string", notNull: true, defaultValue: '""' },
      { name: "age", type: "int", notNull: true, defaultValue: "0" },
      { name: "breed", type: "multiple" },
      { name: "image", type: "string", notNull: true, defaultValue: '""' },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Dogs = InferredTypes["dogs"];
export type DogsRecord = Dogs & XataRecord;

export type DatabaseSchema = {
  dogs: DogsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://erikras-90i0hi.us-east-1.xata.sh/db/postman-dogs",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
